### PR TITLE
[Hacktoberfest] A few code quality issues

### PR DESCRIPTION
**Pull request by lpegoraro**
Remove the ` quote and use double quote for Table names in SQL.
Added a newer equals and hashCode in ArchiveIdentifierVersion.

## Type of request
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring 
- [ ] Documentation or documentation changes

## Related Issue(s)
Relates to #35 

## Concept 
This fixes a few issues in the following code quality issues:
https://app.codacy.com/manual/aposin-bot/LicenseScout/issues?bid=12903434&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19XQ==

#### Initiator
Luiz Henrique Pegoraro / github.com/lpegoraro

#### How has this Tested?
Ran SQL locally in dockerized MySQL db.
Ran unit tests in core module.
Screenshot_20191001_112455

## Checklist:
- [x] My code follows the code style of this project.
- [x] I agree with die CLA.
- [x] I have read the CONTRIBUTING docs.
- [ ] I have added/updated necessary documentation (if appropriate). (N/A)

### CODE REVIEW

**Comment by d-gs** [comment]
Hello @lpegoraro - thank you very much for your interest in our project! Before we can assign a maintainer for this PR, could you please sign the CLA (see https://github.com/aposin/LicenseScout/pull/39#issuecomment-537061772)?

**Comment by lpegoraro** [comment]
Signed, I was having a few issues in my browser and CLA was not working properly. Now I got it.

**Comment by d-gs** [comment]
Thanks you @lpegoraro - @pfistererm, could you review the changes of this PR?

**Comment by d-gs** [comment]
@lpegoraro, some extra-requirement that I forgot to mention: you have to sign your commits before we can merge this PR after review (more information about signing commits in GitHub [here](https://help.github.com/en/articles/signing-commits)). Sorry for any inconvenience.

**Comment by lpegoraro** [comment]
Thanks!

**Comment by d-gs** [comment]
@lpegoraro - we are almost ready to merge these changes, but we still need that you sign your commits. Sorry for the inconvenience.

You can check the [GitHub help on how to sign commits](https://help.github.com/en/articles/signing-commits) if you are not familiar with the procedure.

**Comment by StefanFranzWeiser** [comment]
Sorry, but your commits are not signed. Our project only accepts signed commits. Have a look at [https://help.github.com/en/articles/about-commit-signature-verification](https://help.github.com/en/articles/about-commit-signature-verification).

Can you please do that, so we can accept your contribution? :blush:

**Comment by lpegoraro** [comment]
Yeah sorry about that, I will sign them and correct it right away

**Comment by lpegoraro** [comment]
I needed to migrate to a different branch, please go to #41. Thanks!

**Pull request closed without merging**
